[package]
name = "amlcli"
version = "0.1.0"
authors = ["roman <romix.lab@gmail.com>"]
edition = "2018"

[dependencies]
yaml-rust = "0.4"
linked-hash-map = "0.5.2"
tera = "0.11"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.9"
serde_json = "1.0"